version: "3"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: RunningMan323#
      ACCEPT_EULA: Y
      SQL_SERVER_AGENT_ENABLED: "true"
    restart: unless-stopped
    networks:
      - keycloak-metrics-network
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql


volumes:
  mssql_data:
