version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin 
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana-storage:/var/lib/grafana 
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./datasources:/etc/grafana/provisioning/datasources
      - ./dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000" 
    restart: unless-stopped 
    networks:
      - keycloak-metrics-network

    depends_on:
      - prometheus

volumes:
  grafana-storage:
