version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin 
    volumes:
      - grafana-storage:/var/lib/grafana 
      - grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000" 
    restart: unless-stopped 
    networks:
      - keycloak-metrics-network

volumes:
  grafana-storage:
