version: "3"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml" # Specify the config file
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - keycloak-metrics-network
    depends_on:
      - metric-exporter

volumes:
  prometheus_data:
